# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-07 11:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Blogs', '0001_initial'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='anonymous', max_length=255)),
                ('collection', models.ManyToManyField(related_name='cards', to='Blogs.Cards')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_journal', to='Users.UserProfile')),
            ],
            options={
                'verbose_name': 'MyJournals',
                'verbose_name_plural': 'MyJournals',
            },
        ),
    ]
