# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-07 11:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Blogs', '0001_initial'),
        ('Users', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogs', models.ManyToManyField(blank=True, related_name='blog_in_cat', to='Blogs.Cards')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cat_name', to='categories.Categories')),
            ],
            options={
                'verbose_name': 'Blogs in Categories',
                'verbose_name_plural': 'Blogs in Categories',
            },
        ),
        migrations.CreateModel(
            name='CategoryFollowers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.ManyToManyField(blank=True, related_name='cat_followed', to='categories.Categories')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cat_follower', to='Users.UserProfile')),
            ],
            options={
                'verbose_name': 'User Folllowing Categories',
                'verbose_name_plural': 'User Folllowing Categories',
            },
        ),
    ]
