# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-07 11:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import froala_editor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='Cards', verbose_name='Banner Image for your blog')),
                ('desc', froala_editor.fields.FroalaField(blank=True, null=True)),
                ('v_type', models.CharField(choices=[('public', 'public'), ('private', 'private')], default='public', max_length=125)),
                ('likes', models.IntegerField(default=0)),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Uploaded On')),
                ('user', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.UserProfile')),
            ],
            options={
                'verbose_name': 'Blogs',
                'verbose_name_plural': 'Blogs',
            },
        ),
    ]
