# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-08 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0002_cards_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='blog_category',
            field=models.ManyToManyField(blank=True, to='categories.Categories'),
        ),
    ]
