# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-08 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0003_auto_20170608_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='blog_category',
            field=models.ManyToManyField(blank=True, related_name='category', to='categories.Categories'),
        ),
    ]
