# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-10 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0004_auto_20170608_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='slug',
            field=models.SlugField(default='nothing', unique=True),
        ),
    ]
