# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-13 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0006_auto_20170613_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
    ]
