# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-07 11:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Blogs', '0001_initial'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardLikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.IntegerField(default=0)),
                ('like_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('like_on_card', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_likes', to='Blogs.Cards')),
                ('user', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_likes', to='Users.UserProfile')),
            ],
            options={
                'verbose_name': 'Like',
            },
        ),
    ]
