# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-07 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=25, unique=True)),
                ('image', models.ImageField(default='no-image.png', upload_to='Categories', verbose_name='Category Image')),
                ('user_count', models.IntegerField(default=0)),
                ('blog_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Categories',
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
