# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-07 11:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('following_since', models.DateTimeField(default=django.utils.timezone.now)),
                ('followed_by', models.ManyToManyField(related_name='followed_bys', to='Users.UserProfile')),
                ('follows', models.ManyToManyField(related_name='follow', to='Users.UserProfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='Users.UserProfile')),
            ],
            options={
                'verbose_name': 'Followers',
                'verbose_name_plural': 'Followers',
            },
        ),
    ]
