"""
Django settings for sight2 project.

Generated by 'django-admin startproject' using Django 1.10.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'rc6gt9$rw2n1@wq%n37lh+!y4(zxu#uc8pgcenr$!7+r452fta'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # custom apps
    "Users",
    "Blogs",
    "Comments",
    "Likes",
    "Home",
    'crispy_forms',
    "froala_editor",
    "followers",
    "journal",
    "categories",
    "FollowCategory",
    'social_django',
]
CONTEXT_PROCESSORS=(
    'django.core.context_processors.request',
    
)
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # custom
    'social_django.middleware.SocialAuthExceptionMiddleware',
]

ROOT_URLCONF = 'sight2.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # 
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect', 
            ],
        },
    },
]

WSGI_APPLICATION = 'sight2.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = (
    'social_core.backends.github.GithubOAuth2',
    'social_core.backends.twitter.TwitterOAuth',
    'social_core.backends.facebook.FacebookOAuth2',
    'social_core.backends.google.GoogleOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)

LOGIN_URL = '/users/login/'
LOGOUT_URL = '/users/logout'
LOGIN_REDIRECT_URL = '/'

# github
SOCIAL_AUTH_GITHUB_KEY = '1fd0b63049a6afe58a47'
SOCIAL_AUTH_GITHUB_SECRET = '6eac7fe15a22f25e928ae4938ba10e78fefa82e1'

# facebook
SOCIAL_AUTH_FACEBOOK_KEY = '1816052605375433'  # App ID
SOCIAL_AUTH_FACEBOOK_SECRET = 'a7419dc45661aacc6d92c272f6a0f246'  # App Secret
SOCIAL_AUTH_FACEBOOK_SCOPE = ['email']
SOCIAL_AUTH_FACEBOOK_PROFILE_EXTRA_PARAMS = {
    'fields': 'id,name,email', 
}

# google
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY='244330048447-rce99001n0p1906lrkvbsg6vjhvciju9'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET='ScxviNMLHNdfl3AUBdjb6IiB'
SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE = [""]

SOCIAL_AUTH_PIPELINE = (

    'social_core.pipeline.social_auth.social_details',

    'social_core.pipeline.social_auth.social_uid',

    'social_core.pipeline.social_auth.auth_allowed',

    'social_core.pipeline.social_auth.social_user',

    'social_core.pipeline.user.get_username',
    'social_core.pipeline.social_auth.associate_by_email',

    'social_core.pipeline.user.create_user',

    'Home.views.save_profile',

    'social_core.pipeline.social_auth.associate_user',

    'social_core.pipeline.social_auth.load_extra_data',

    'social_core.pipeline.user.user_details',


)


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'


STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static")
]

STATIC_ROOT = os.path.join(BASE_DIR + '/static_root/')

MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR + '/media/')

CRISPY_TEMPLATE_PACK = 'bootstrap3'
FROALA_EDITOR_OPTIONS={
    'dragInline': True,
}
FROALA_EDITOR_PLUGINS = ('colors', 'font_family','image', 'quote','video')

FROALA_EDITOR_THEME= 'dark'
EMAIL_HOST = "smtp.gmail.com"
EMAIL_HOST_USER = "dev.facelook@gmail.com"
EMAIL_HOST_PASSWORD = 'devdevdev'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
